version: '3.5'

networks:
	localdev:
		name: localdev


services:
	main-api:
		build: Chirp/
		restart: always
		port:
			- "7000:80"
		depends_on:
			- db-server
			- redis
		networks:
			- localdev

	db-server:
		image: microsoft/mssql-servere-linux:2017-latest
		container_name: db-server
		environment:
			- ACCEPT_EULA=y
			- MSSQL_SA_PASSWORD=Admin123
			- MSSQL_TCP_PORT=1433
		ports:
			- "1400:1433"
		networks:
			- localdev

	redis:
		image: redis
		container_name: redis
		ports:
			- "6379:6379""